version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - solar-net

 
  redis:
    image: redis:alpine
    container_name: redis_cache_solar
    ports:
      - "6379:6379"
    networks:
      - solar-net

networks:
  solar-net:
    driver: bridge
